### PR TITLE
New "Electro Vehicle" Theme

### PR DESCRIPTION
**Pull request by mkwatchface**
This pull request is implementing a new theme called "Electro Vehicle". The theme consists of newly designed gauges, a new background matching the theme and a new bold sporty font. All changes have been also tested in car while driving to ensure readability in a glance.

20231105_104356 copy

Other changes:
Adjusted the ticks padding of the already existing "Skoda Monte Carlo" theme to bring the numbers closer to the graphic.

Please for an additional review and test of the changes prior to release.

### CODE REVIEW

**Comment by agronick** [comment]
Baller! Nice work. You know how to work a camera and get shots that look professional. If you want to get a pic of this I'll add it to the readme.

**Comment by agronick** [comment]
@mkwatchface there is one issue. The gauges aren't drawn the in the same spots on every car and the chart view has no gauges so the blue glow can be out of place. Can you move the blue glow to the gauge images instead of the background in another pr even if the glow has to be shrunk? Thanks.

**Comment by mkwatchface** [comment]
I am thinking that the image of each gauge is 480x480 and the actual gauge is very close to the edge. If we incorporate the glow on the gauge it will be very small glow. Additionally, i made a shadow under the gauges thinking that the background will be light and its gonna be visible. If you allow me some time I will think about it and come up with a solution.

Till then, please don't release as I would like everyone to have top quality!

**Comment by mkwatchface** [comment]
Hi Kyle,

I think i have now a solution to the above issue. What i did, was to make the glow smaller and incorporate it to the gauge image. Then i changed the background a bit to have it's glow in the middle and the sides (bottom) of the image so it would match every screen. It looks like this:



In order to avoid creating pull requests, could i ask you to download the apk from this repo https://github.com/mkwatchface/aa-torque/releases and install it, test it, and if you are fine with it i can create the pull request. If futher adjustment are required you can let me know!

Thank you

**Comment by agronick** [comment]
I don't think I can see your releases unless you take them out of draft. I copied the code down locally. You want to taper the edges of the background to black so it doesn't look cut off on large screens. I positioned the backgrounds at the top. Someone made a PR to remove the lines from the top of the background so I'm going to move them back to the center. You need at least a small liner gradient either going to #000 or going to 0 on the alpha channel in order for it not to look chopped off. Other than that great work.

**Comment by mkwatchface** [comment]
Hi Kyle, I will try your suggestion, however I believe that this change will "hide" the shadow of the gauges. If you apply a dark background on the gauges you will see what I mean. Let me give it a try, post a picture and we discuss further... In the meantime, if you have a bigger screen infotainment that you can post a picture of how it looks on a bigger screen I would appreciate it... unfortunately, I only have one car and my screen is quite small...

**Comment by agronick** [comment]
This is how it looks on mine  it is getting a hard border at the top and before the bottom of the screen.

**Comment by agronick** [comment]
Also you may want to put the shadow below the glow. The bottom feels kind of egg shaped. Not sure if thats intentional or not.

**Comment by mkwatchface** [comment]
> This is how it looks on mine 
> 
> it is getting a hard border at the top and before the bottom of the screen.

I see now what you mean... you have the Taskbar on the left side and that leaves the bottom of your screen blank. In my car, the Taskbar is down and actually I liked the contrast that was making. Anyway, I made some adjustments fading the background to black so it should be smoother. Also, I placed the glow above the shadow for shake of realism however now the shadow looks smaller. I placed the shadow a bit more down to mitigate this as much as I could.

I am not in my car but here is a screenshot from the phone. Please note that I own a galaxy fold 4 and its aspect ratio is very unusual but it will do for now...

You can download the images again from the repo and if you like it let me know so I can create a pull request to merge it:

**Pull request merged**
